name: Run Lead Scraper

on:
  schedule:
    # Runs at 02:00 UTC (around 7:30 AM IST)
    - cron: '0 2 * * *'
    # Runs at 14:00 UTC (around 7:30 PM IST)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install gspread requests beautifulsoup4 phonenumbers

      - name: Create Google Credentials File
        env:
          GSHEET_CREDS: ${{ secrets.GSHEET_CREDS }}
        run: echo "$GSHEET_CREDS" > credentials.json

      - name: Run Python Script
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          GSHEET_NAME: ${{ secrets.GSHEET_NAME }}
        run: python discover_sites.py
