name: Run Lead Scraper

on:
  schedule:
    # Runs once daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Set a 6-hour timeout for the job

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create Google Credentials File
        run: |
          echo "${{ secrets.GSHEET_CREDS }}" | base64 --decode > credentials.json

      - name: Run Python Script
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          GSHEET_NAME: ${{ secrets.GSHEET_NAME }}
        run: python discover_sites.py

      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lead-discovery-log
          path: lead_discovery.log
